### ISSUE TITLE
failed to decrypt

### ISSUE THREAD

**Issue by justmwa** [TeamWin/android_device_leeco_s2#1]
Hello,
crypting the phone wasn't a great idea since twrp won't accept neither schemas nor PIN codes (failed to decrypt data), using official LineageOS.
how can I help debug this?

**Comment by rishabhrao** [comment]
Thanks to @codeworkx this issue seems to be fixed for now...
A new build will fix it for you...

**Comment by justmwa** [comment]
Indeed, thanks @codeworkx
